### ISSUE TITLE
WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider HiveAcid

### ISSUE THREAD

**Issue by dohongdayi** [qubole/spark-acid#16]
While running HiveACIDSuite, I keep receiving following warnings:

WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider HiveAcid. Persisting data source table `HiveTestDB`.`spark_t1` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.

How do I prevent these warnings?

Thanks.

**Comment by somani** [comment]
Yeah this warning can't be avoided as it stands today, and is expected and should not be a problem. This happens because we try to create a symlink table with HiveAcid format, but Spark doesn't know whats the corresponding hive serde for it, so it warns that Hive will not be able to use it.
That is fine because we don't want the symlink table to be used in Hive anyway, and just to be used in spark.

FYI: This is what I mean by symlink table: https://github.com/qubole/spark-acid#sql

**Comment by dohongdayi** [comment]
But these warnings are annoying, I think we should leave this issue open until we avoid them.

**Comment by citrusraj** [comment]
https://github.com/qubole/spark-acid/commit/2e66f76b3a3c974a73f03d9e80d9c66a0475a552

not need to create symlink table anymore...
